# fly.toml file generated for gbot-v5ranger on 2023-02-22T05:14:01+09:00

app = "gbot-v5ranger"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  NODE_OPTIONS="--max-old-space-size=192"
  SWAP="true"

[experimental]
  auto_rollback = true